% sorting hyperparameters
function hp = sorting_hyperparameters_in()

    hp = struct(...
        ... % Hyperparameters for MLP 
        'numHidLayer',             4, ...                        % Number of hidden layers in MLP
        'hiddenLayerSize',         [2028, 1024, 128, 128], ...   % Size of each hidden layer in MLP
        'mlpLossFcn',              'mse',...                     % Loss function for MLP ('mse' or 'mae')
        ...
        ... % Hyperparameters for CNN
        'numConvBlocks',           4, ...                        % Number of convolutional blocks in CNN
        'filterSize',              3, ...                        % Size of convolutional filters in CNN
        'numFilters',              [16, 32, 64, 128], ...        % Number of filters in each CNN block
        'poolSize',                2, ...                        % Pooling size in CNN
        'cnnLossFcn',              'crossentropy',...            % Loss function for CNN ('crossentropy' or 'dlconv')
        'dropoutRate',             [0.01, 0.01, 0.01, 0.01], ... % Dropout rate for each CNN layer (also  shared with MLP)
        ...
        ... % Training Hyperparameters 
        'maxEpochs',               20, ...                       % Maximum number of training epochs
        'miniBatchSize',           128, ...                      % Mini-batch size for training
        'initialLearningRate',     1e-4, ...                     % Initial learning rate
        'learningRateDropFactor',  0.1, ...                      % Factor to drop the learning rate
        'learningRateDropPeriod',  10, ...                       % Period (in epochs) to drop the learning rate
        'l2Reg',                   1e-4, ...                     % L2 regularization parameter
        'gradientThreshold',       1, ...                        % Gradient clipping threshold
        'validationRatio',         0.2, ...                      % Ratio of data used for validation
        'executionEnvironment',    'auto', ...                   % Execution environment ('auto', 'cpu', 'gpu')
        ...
        ... % Hyperparameters for GBM 
        'NumLearningCycles',       150, ...                      % Number of learning cycles in GBM
        'LearnRate',               0.1, ...                      % Learning rate for GBM
        'MaxNumSplits',            10, ...                       % Maximum number of splits in each tree (GBM)
        'MinLeafSize',             2, ...                        % Minimum leaf size in each tree (GBM)
        ...
        ... % Hyperparameters for SVM 
        'KernelFunction',          'polynomial', ...             % Kernel function type for SVM ('linear', 'polynomial', 'rdf', 'auto')
        'PolynomialOrder',         3, ...                        % Order of the polynomial kernel (SVM)
        'BoxConstraint',           1, ...                        % Box constraint parameter for SVM
        'KernelScale',             'auto', ...                   % Kernel scale parameter for SVM
        ...
        'UseParallel',             false ...                     % parallel processing for training neural nets
    );

    % HP Variable Names for GUI 
    hp.varName = struct(...
        ... % MLP Hyperparameters
        'numHidLayer',             'MLP: Number of Hidden Layers', ...
        'hiddenLayerSize',         'MLP: Hidden Layer Sizes', ...
        'mlpLossFcn',              'MLP: Loss Function', ...
        ...
        ... % CNN Hyperparameters
        'numConvBlocks',           'CNN: Number of Conv Blocks', ...
        'filterSize',              'CNN: Filter Size', ...
        'numFilters',              'CNN: Filters per Block', ...
        'poolSize',                'CNN: Pooling Size', ...
        'cnnLossFcn',              'CNN: Loss Function', ...
        'dropoutRate',             'CNN/MLP: Dropout Rates', ...
        ...
        ... % Training Hyperparameters
        'maxEpochs',               'Training: Max Epochs', ...
        'miniBatchSize',           'Training: Mini Batch Size', ...
        'initialLearningRate',     'Training: Initial Learning Rate', ...
        'learningRateDropFactor',  'Training: Learning Rate Drop Factor', ...
        'learningRateDropPeriod',  'Training: Learning Rate Drop Period', ...
        'l2Reg',                   'Training: L2 Regularization', ...
        'gradientThreshold',       'Training: Gradient Threshold', ...
        'validationRatio',         'Training: Validation Ratio', ...
        'executionEnvironment',    'Training: Execution Environment', ...
        ...
        ... % GBM Hyperparameters
        'NumLearningCycles',       'GBM: Learning Cycles', ...
        'LearnRate',               'GBM: Learning Rate', ...
        'MaxNumSplits',            'GBM: Max Splits', ...
        'MinLeafSize',             'GBM: Min Leaf Size', ...
        ...
        ... % SVM Hyperparameters
        'KernelFunction',          'SVM: Kernel Function', ...
        'PolynomialOrder',         'SVM: Polynomial Order', ...
        'BoxConstraint',           'SVM: Box Constraint', ...
        'KernelScale',             'SVM: Kernel Scale', ...
        ...
        ... % Miscellaneous Hyperparameters
        'UseParallel',             'Use Parallel Processing' ...
    );
end